In [1]:
# imports

from scipy.io import loadmat
import numpy as np

In [2]:
avi_data = list()
for i in range(1,5):
    avi_data.append(loadmat(f"datasets/avi/single/Sub{i}_singletarget.mat"))

In [3]:
# extração direta dos dados

X = [d['Data'][0][0][0] for d in avi_data]
y = [d['Data'][0][0][1] for d in avi_data]

print("Divisão dos dados:")
for data in X:
    print(data.shape)

print("\nDivisão dos rótulos (sequências):")
for data in y:
    print(data)

Divisão dos dados:
(15360, 27)
(15360, 26)
(15360, 21)
(15360, 21)

Divisão dos rótulos (sequências):
[[10.  10.  10.  12.  12.  12.   6.5  6.5  6.5  6.   6.   6.   6.   6.
   6.   7.5  7.5  7.5  7.   7.   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.
   7.   7.   7.   7.   7.   8.2  8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]
[[10.  10.  10.   6.5  6.5  6.5  6.   6.   6.   7.5  7.5  7.5  7.   7.
   7.   8.2  8.2  8.2  9.3  9.3  9.3]]


In [4]:

# padronizando 1º participante

X1 = X[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]
y1 = y[0][:, list(set(range(27)) - set([3, 4, 5, 12, 13, 14]))]
X1.shape, y1.shape

((15360, 21), (1, 21))

In [5]:
# salva os dados numpy

np.save("datasets/avi/single/data_sub1.npy", X1)
np.save("datasets/avi/single/labels_sub1.npy", y1)

In [16]:
avi_data_mult = list()
for i in range(1,6):
    for j in range(1,3):
        avi_data_mult.append(loadmat(f"datasets/avi/multi/Sub{i}_{j}_multitarget.mat"))


agroup_relatives = [[]]

for i in range(0, len(avi_data_mult), 2):
    group = [avi_data_mult[i], avi_data_mult[i + 1]]
    agroup_relatives.append(group)

In [26]:
X = [d['Data'][0][0][7] for d in avi_data_mult]
y = [d['Data'][0][0][8][0] for d in avi_data_mult]

print('\nDivisão dos dados:\n')
for data in X:
      print(np.array(data).shape, data.swapaxes(0,1).shape)

print('\nDivisão dos rótulos (sequências):\n')
for data in y:
      print(data)


Divisão dos dados:

(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)
(8192, 10) (10, 8192)

Divisão dos rótulos (sequências):

[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
[7.5 8.2 7.  8.2 6.  7.5 6.  6.  8.2 8.2]
[9.3 6.  6.  8.2 6.  6.5 7.5 7.  6.  6. ]
